name: Ensure Node.js compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 10.0.0
        - 10.1.x
        - 10.2.x
        - 10.3.x
        - 10.4.x
        - 10.5.x
        - 10.6.x
        - 10.7.x
        - 10.8.x
        - 10.9.x
        - 10.10.x
        - 10.11.x
        - 10.12.x
        - 10.13.x
        - 10.14.x
        - 10.15.x
        - 10.16.x
        - 10.17.x
        - 10.18.x
        - 11.1.x
        - 11.2.x
        - 11.3.x
        - 11.4.x
        - 11.5.x
        - 11.6.x
        - 11.7.x
        - 11.8.x
        - 11.9.x
        - 11.10.x
        - 11.11.x
        - 11.12.x
        - 11.13.x
        - 11.14.x
        - 11.15.x
        - 12.0.x
        - 12.1.x
        - 12.2.x
        - 12.3.x
        - 12.4.x
        - 12.5.x
        - 12.6.x
        - 12.7.x
        - 12.8.x
        - 12.9.x
        - 12.10.x
        - 12.11.x
        - 12.12.x
        - 12.13.x
        - 12.14.x
        - 13.0.x
        - 13.1.x
        - 13.2.x
        - 13.3.x
        - 13.4.x
        - 13.5.x
        - 13.6.x
        - 13.7.x
        - 14.0.x
        - 14.1.x
        - 14.2.x
        - 14.3.x
        - 14.4.x
        - 14.5.x
        - 14.6.x
        - 14.7.x
        - 14.8.x
        - 14.9.x
        - 14.10.x
        - 14.11.x
        - 14.12.x
        - 14.13.x
        - 14.14.x
        - 15.0.x
        - 15.1.x
        - 15.2.x
        - 15.3.x
        - 15.4.x
        - 15.5.x
        - 15.6.x
        - 15.7.x
        - 15.8.x
        - 15.9.x
        - 15.10.x
        - 15.11.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
